# copy from https://github.com/tauri-apps/tauri-action
name: 'tests'
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        # todo ubuntu-20.04
        platform: ['windows-latest', 'macos-latest']

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: install frontend dependencies
        run: pnpm install

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri/

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: test build
        run: pnpm tauri build
